"""schema v1 initial

Revision ID: 7678848a9056
Revises:
Create Date: 2026-10-01 17:11:19.586002
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7678848a9056'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefit_type',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.CheckConstraint('length(btrim(code)) > 0', name=op.f('ck_benefit_type_code_not_blank')),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_benefit_type_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benefit_type')),
    sa.UniqueConstraint('code', name=op.f('uq_benefit_type_code'))
    )
    op.create_table('exam',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('length(btrim(code)) > 0', name=op.f('ck_exam_code_not_blank')),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_exam_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam')),
    sa.UniqueConstraint('code', name=op.f('uq_exam_code'))
    )
    op.create_table('funding_type',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.CheckConstraint('length(btrim(code)) > 0', name=op.f('ck_funding_type_code_not_blank')),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_funding_type_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funding_type')),
    sa.UniqueConstraint('code', name=op.f('uq_funding_type_code'))
    )
    op.create_table('olympiad',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('organizer', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_olympiad_name_not_blank')),
    sa.CheckConstraint('level > 0', name=op.f('ck_olympiad_level_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_olympiad'))
    )
    op.create_table('olympiad_result_type',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.CheckConstraint('length(btrim(code)) > 0', name=op.f('ck_olympiad_result_type_code_not_blank')),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_olympiad_result_type_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_olympiad_result_type')),
    sa.UniqueConstraint('code', name=op.f('uq_olympiad_result_type_code'))
    )
    op.create_table('ontology_object_type',
    sa.Column('api_name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('backing_table', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("api_name ~ '^[a-z][a-z0-9_]*$'", name=op.f('ck_ontology_object_type_api_name_snake_case')),
    sa.CheckConstraint('length(btrim(display_name)) > 0', name=op.f('ck_ontology_object_type_display_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_object_type')),
    sa.UniqueConstraint('api_name', name='uq_ontology_object_type_api_name')
    )
    op.create_table('policy_rule_type',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.CheckConstraint('length(btrim(code)) > 0', name=op.f('ck_policy_rule_type_code_not_blank')),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_policy_rule_type_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_rule_type')),
    sa.UniqueConstraint('code', name=op.f('uq_policy_rule_type_code'))
    )
    op.create_table('quota_type',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.CheckConstraint('length(btrim(code)) > 0', name=op.f('ck_quota_type_code_not_blank')),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_quota_type_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quota_type')),
    sa.UniqueConstraint('code', name=op.f('uq_quota_type_code'))
    )
    op.create_table('source_type',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.CheckConstraint('length(btrim(code)) > 0', name=op.f('ck_source_type_code_not_blank')),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_source_type_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_type')),
    sa.UniqueConstraint('code', name=op.f('uq_source_type_code'))
    )
    op.create_table('subject_area',
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name=op.f('ck_subject_area_not_own_parent')),
    sa.ForeignKeyConstraint(['parent_id'], ['subject_area.id'], name=op.f('fk_subject_area_parent_id_subject_area'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject_area'))
    )
    op.create_index('ix_subject_area_parent', 'subject_area', ['parent_id'], unique=False)
    op.create_table('university',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('length(btrim(code)) > 0', name=op.f('ck_university_code_not_blank')),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_university_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_university')),
    sa.UniqueConstraint('code', name=op.f('uq_university_code'))
    )
    op.create_table('user_profile',
    sa.Column('school_grade', sa.Integer(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('graduation_year IS NULL OR graduation_year >= 1900', name=op.f('ck_user_profile_graduation_year_valid')),
    sa.CheckConstraint('school_grade IS NULL OR school_grade > 0', name=op.f('ck_user_profile_school_grade_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile'))
    )
    op.create_table('admission_campaign',
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('application_start', sa.Date(), nullable=True),
    sa.Column('application_end', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('application_start IS NULL OR application_end IS NULL OR application_end >= application_start', name=op.f('ck_admission_campaign_application_dates_ordered')),
    sa.CheckConstraint('year >= 1900', name=op.f('ck_admission_campaign_year_valid')),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], name=op.f('fk_admission_campaign_university_id_university'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admission_campaign')),
    sa.UniqueConstraint('id', 'university_id', name='uq_admission_campaign_id_university'),
    sa.UniqueConstraint('university_id', 'year', name='uq_admission_campaign_university_year')
    )
    op.create_table('course',
    sa.Column('subject_area_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_course_name_not_blank')),
    sa.ForeignKeyConstraint(['subject_area_id'], ['subject_area.id'], name=op.f('fk_course_subject_area_id_subject_area'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course')),
    sa.UniqueConstraint('subject_area_id', 'name', name='uq_course_subject_area_name')
    )
    op.create_table('department',
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('length(btrim(code)) > 0', name=op.f('ck_department_code_not_blank')),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_department_name_not_blank')),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], name=op.f('fk_department_university_id_university'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department')),
    sa.UniqueConstraint('id', 'university_id', name='uq_department_id_university'),
    sa.UniqueConstraint('university_id', 'code', name='uq_department_university_code')
    )
    op.create_table('object_ref',
    sa.Column('object_type_id', sa.UUID(), nullable=False),
    sa.Column('primary_key_value', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('length(btrim(primary_key_value)) > 0', name=op.f('ck_object_ref_primary_key_value_not_blank')),
    sa.ForeignKeyConstraint(['object_type_id'], ['ontology_object_type.id'], name=op.f('fk_object_ref_object_type_id_ontology_object_type'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_object_ref')),
    sa.UniqueConstraint('id', 'object_type_id', name='uq_object_ref_id_type'),
    sa.UniqueConstraint('object_type_id', 'primary_key_value', name='uq_object_ref_type_primary_key')
    )
    op.create_table('olympiad_profile',
    sa.Column('olympiad_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_olympiad_profile_name_not_blank')),
    sa.ForeignKeyConstraint(['olympiad_id'], ['olympiad.id'], name=op.f('fk_olympiad_profile_olympiad_id_olympiad'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_olympiad_profile')),
    sa.UniqueConstraint('olympiad_id', 'name', name='uq_olympiad_profile_olympiad_name')
    )
    op.create_table('ontology_link_type',
    sa.Column('source_type_id', sa.UUID(), nullable=False),
    sa.Column('target_type_id', sa.UUID(), nullable=False),
    sa.Column('api_name', sa.Text(), nullable=False),
    sa.Column('cardinality', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("api_name ~ '^[a-z][a-z0-9_]*$'", name=op.f('ck_ontology_link_type_api_name_snake_case')),
    sa.CheckConstraint("cardinality IN ('one_to_one', 'one_to_many', 'many_to_one', 'many_to_many')", name=op.f('ck_ontology_link_type_cardinality_valid')),
    sa.ForeignKeyConstraint(['source_type_id'], ['ontology_object_type.id'], name=op.f('fk_ontology_link_type_source_type_id_ontology_object_type'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_type_id'], ['ontology_object_type.id'], name=op.f('fk_ontology_link_type_target_type_id_ontology_object_type'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_link_type')),
    sa.UniqueConstraint('api_name', name='uq_ontology_link_type_api_name'),
    sa.UniqueConstraint('id', 'source_type_id', 'target_type_id', name='uq_ontology_link_type_id_endpoints')
    )
    op.create_index('ix_ontology_link_type_source_type', 'ontology_link_type', ['source_type_id'], unique=False)
    op.create_index('ix_ontology_link_type_target_type', 'ontology_link_type', ['target_type_id'], unique=False)
    op.create_table('ontology_property_type',
    sa.Column('object_type_id', sa.UUID(), nullable=False),
    sa.Column('api_name', sa.Text(), nullable=False),
    sa.Column('data_type', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("api_name ~ '^[a-z][a-z0-9_]*$'", name=op.f('ck_ontology_property_type_api_name_snake_case')),
    sa.CheckConstraint("data_type IN ('string', 'integer', 'decimal', 'boolean', 'date', 'datetime', 'json', 'uuid')", name=op.f('ck_ontology_property_type_data_type_valid')),
    sa.ForeignKeyConstraint(['object_type_id'], ['ontology_object_type.id'], name=op.f('fk_ontology_property_type_object_type_id_ontology_object_type'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_property_type')),
    sa.UniqueConstraint('id', 'object_type_id', name='uq_ontology_property_type_id_object_type'),
    sa.UniqueConstraint('object_type_id', 'api_name', name='uq_ontology_property_type_object_api')
    )
    op.create_table('policy_rule',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('rule_type_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('length(btrim(code)) > 0', name=op.f('ck_policy_rule_code_not_blank')),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_policy_rule_name_not_blank')),
    sa.ForeignKeyConstraint(['rule_type_id'], ['policy_rule_type.id'], name=op.f('fk_policy_rule_rule_type_id_policy_rule_type'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_rule')),
    sa.UniqueConstraint('code', name=op.f('uq_policy_rule_code'))
    )
    op.create_index('ix_policy_rule_rule_type', 'policy_rule', ['rule_type_id'], unique=False)
    op.create_table('program',
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('degree_level', sa.Text(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('duration_months > 0', name=op.f('ck_program_duration_months_positive')),
    sa.CheckConstraint('length(btrim(code)) > 0', name=op.f('ck_program_code_not_blank')),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_program_name_not_blank')),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], name=op.f('fk_program_university_id_university'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program')),
    sa.UniqueConstraint('id', 'university_id', name='uq_program_id_university'),
    sa.UniqueConstraint('university_id', 'code', name='uq_program_university_code')
    )
    op.create_table('source',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source_type_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_source_name_not_blank')),
    sa.ForeignKeyConstraint(['source_type_id'], ['source_type.id'], name=op.f('fk_source_source_type_id_source_type'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source'))
    )
    op.create_index('ix_source_source_type', 'source', ['source_type_id'], unique=False)
    op.create_table('user_exam',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.CheckConstraint('score >= 0', name=op.f('ck_user_exam_score_nonnegative')),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name=op.f('fk_user_exam_exam_id_exam'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], name=op.f('fk_user_exam_profile_id_user_profile'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('profile_id', 'exam_id', name=op.f('pk_user_exam'))
    )
    op.create_index('ix_user_exam_exam', 'user_exam', ['exam_id'], unique=False)
    op.create_table('curriculum',
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('length(btrim(version)) > 0', name=op.f('ck_curriculum_version_not_blank')),
    sa.CheckConstraint('start_year >= 1900', name=op.f('ck_curriculum_start_year_valid')),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], name=op.f('fk_curriculum_program_id_program'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curriculum')),
    sa.UniqueConstraint('program_id', 'version', name='uq_curriculum_program_version')
    )
    op.create_table('policy_rule_version',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published')", name=op.f('ck_policy_rule_version_status_valid')),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name=op.f('ck_policy_rule_version_validity_ordered')),
    sa.CheckConstraint('version > 0', name=op.f('ck_policy_rule_version_version_positive')),
    sa.ForeignKeyConstraint(['rule_id'], ['policy_rule.id'], name=op.f('fk_policy_rule_version_rule_id_policy_rule'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_rule_version')),
    sa.UniqueConstraint('id', 'rule_id', name='uq_policy_rule_version_id_rule'),
    sa.UniqueConstraint('rule_id', 'version', name='uq_policy_rule_version_rule_version')
    )
    op.create_index('ix_policy_rule_version_published_validity', 'policy_rule_version', ['valid_from', 'valid_to'], unique=False, postgresql_where=sa.text("status = 'published'"))
    op.create_table('program_department',
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['department_id', 'university_id'], ['department.id', 'department.university_id'], name='fk_program_department_department_university', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id', 'university_id'], ['program.id', 'program.university_id'], name='fk_program_department_program_university', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('program_id', 'department_id', name=op.f('pk_program_department'))
    )
    op.create_index('ix_program_department_department_university', 'program_department', ['department_id', 'university_id'], unique=False)
    op.create_index('ix_program_department_program_university', 'program_department', ['program_id', 'university_id'], unique=False)
    op.create_table('program_offering',
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('study_form', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('length(btrim(language)) > 0', name=op.f('ck_program_offering_language_not_blank')),
    sa.CheckConstraint('length(btrim(study_form)) > 0', name=op.f('ck_program_offering_study_form_not_blank')),
    sa.ForeignKeyConstraint(['campaign_id', 'university_id'], ['admission_campaign.id', 'admission_campaign.university_id'], name='fk_program_offering_campaign_university', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['program_id', 'university_id'], ['program.id', 'program.university_id'], name='fk_program_offering_program_university', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program_offering')),
    sa.UniqueConstraint('program_id', 'campaign_id', 'study_form', 'language', name='uq_program_offering_business_key')
    )
    op.create_index('ix_program_offering_campaign_university', 'program_offering', ['campaign_id', 'university_id'], unique=False)
    op.create_index('ix_program_offering_program_university', 'program_offering', ['program_id', 'university_id'], unique=False)
    op.create_table('rule_set',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published')", name=op.f('ck_rule_set_status_valid')),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_rule_set_name_not_blank')),
    sa.CheckConstraint('version > 0', name=op.f('ck_rule_set_version_positive')),
    sa.ForeignKeyConstraint(['campaign_id'], ['admission_campaign.id'], name=op.f('fk_rule_set_campaign_id_admission_campaign'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_set')),
    sa.UniqueConstraint('campaign_id', 'name', 'version', name='uq_rule_set_campaign_name_version')
    )
    op.create_table('source_artifact',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('length(btrim(checksum)) > 0', name=op.f('ck_source_artifact_checksum_not_blank')),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_source_artifact_source_id_source'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_artifact')),
    sa.UniqueConstraint('source_id', 'checksum', name='uq_source_artifact_source_checksum')
    )
    op.create_index('ix_source_artifact_source_retrieved_at', 'source_artifact', ['source_id', 'retrieved_at'], unique=False)
    op.create_table('user_olympiad',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('olympiad_profile_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('result_type_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('year >= 1900', name=op.f('ck_user_olympiad_year_valid')),
    sa.ForeignKeyConstraint(['olympiad_profile_id'], ['olympiad_profile.id'], name=op.f('fk_user_olympiad_olympiad_profile_id_olympiad_profile'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], name=op.f('fk_user_olympiad_profile_id_user_profile'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['result_type_id'], ['olympiad_result_type.id'], name=op.f('fk_user_olympiad_result_type_id_olympiad_result_type'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_olympiad')),
    sa.UniqueConstraint('profile_id', 'olympiad_profile_id', 'year', name='uq_user_olympiad_profile_olympiad_year')
    )
    op.create_index('ix_user_olympiad_olympiad_profile', 'user_olympiad', ['olympiad_profile_id'], unique=False)
    op.create_index('ix_user_olympiad_result_type', 'user_olympiad', ['result_type_id'], unique=False)
    op.create_table('competition_pool',
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('funding_type_id', sa.UUID(), nullable=False),
    sa.Column('quota_type_id', sa.UUID(), nullable=False),
    sa.Column('places', sa.Integer(), nullable=False),
    sa.Column('tuition_per_year', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('places >= 0', name=op.f('ck_competition_pool_places_nonnegative')),
    sa.CheckConstraint('tuition_per_year IS NULL OR tuition_per_year >= 0', name=op.f('ck_competition_pool_tuition_nonnegative')),
    sa.ForeignKeyConstraint(['funding_type_id'], ['funding_type.id'], name=op.f('fk_competition_pool_funding_type_id_funding_type'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['offering_id'], ['program_offering.id'], name=op.f('fk_competition_pool_offering_id_program_offering'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quota_type_id'], ['quota_type.id'], name=op.f('fk_competition_pool_quota_type_id_quota_type'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competition_pool')),
    sa.UniqueConstraint('offering_id', 'funding_type_id', 'quota_type_id', name='uq_competition_pool_business_key')
    )
    op.create_index('ix_competition_pool_funding_type', 'competition_pool', ['funding_type_id'], unique=False)
    op.create_index('ix_competition_pool_quota_type', 'competition_pool', ['quota_type_id'], unique=False)
    op.create_table('curriculum_item',
    sa.Column('curriculum_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_hours', sa.Integer(), nullable=False),
    sa.Column('lecture_hours', sa.Integer(), nullable=False),
    sa.Column('practice_hours', sa.Integer(), nullable=False),
    sa.Column('lab_hours', sa.Integer(), nullable=False),
    sa.Column('assessment_type', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('credits >= 0', name=op.f('ck_curriculum_item_credits_nonnegative')),
    sa.CheckConstraint('lab_hours >= 0', name=op.f('ck_curriculum_item_lab_hours_nonnegative')),
    sa.CheckConstraint('lecture_hours + practice_hours + lab_hours <= total_hours', name=op.f('ck_curriculum_item_contact_hours_within_total')),
    sa.CheckConstraint('lecture_hours >= 0', name=op.f('ck_curriculum_item_lecture_hours_nonnegative')),
    sa.CheckConstraint('practice_hours >= 0', name=op.f('ck_curriculum_item_practice_hours_nonnegative')),
    sa.CheckConstraint('semester > 0', name=op.f('ck_curriculum_item_semester_positive')),
    sa.CheckConstraint('total_hours >= 0', name=op.f('ck_curriculum_item_total_hours_nonnegative')),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name=op.f('fk_curriculum_item_course_id_course'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curriculum.id'], name=op.f('fk_curriculum_item_curriculum_id_curriculum'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curriculum_item')),
    sa.UniqueConstraint('curriculum_id', 'course_id', 'semester', name='uq_curriculum_item_course_semester')
    )
    op.create_index('ix_curriculum_item_course', 'curriculum_item', ['course_id'], unique=False)
    op.create_table('fact_assertion',
    sa.Column('object_ref_id', sa.UUID(), nullable=False),
    sa.Column('object_type_id', sa.UUID(), nullable=False),
    sa.Column('property_type_id', sa.UUID(), nullable=False),
    sa.Column('source_artifact_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_fact_assertion_confidence_in_range')),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name=op.f('ck_fact_assertion_validity_ordered')),
    sa.ForeignKeyConstraint(['object_ref_id', 'object_type_id'], ['object_ref.id', 'object_ref.object_type_id'], name='fk_fact_assertion_object_ref_type', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_type_id', 'object_type_id'], ['ontology_property_type.id', 'ontology_property_type.object_type_id'], name='fk_fact_assertion_property_object_type', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['source_artifact.id'], name=op.f('fk_fact_assertion_source_artifact_id_source_artifact'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_assertion'))
    )
    op.create_index('ix_fact_assertion_active_object_property', 'fact_assertion', ['object_ref_id', 'property_type_id'], unique=False, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_index('ix_fact_assertion_object_property_time', 'fact_assertion', ['object_ref_id', 'property_type_id', 'valid_from'], unique=False)
    op.create_index('ix_fact_assertion_object_ref_type', 'fact_assertion', ['object_ref_id', 'object_type_id'], unique=False)
    op.create_index('ix_fact_assertion_property_object_type', 'fact_assertion', ['property_type_id', 'object_type_id'], unique=False)
    op.create_index('ix_fact_assertion_source_artifact', 'fact_assertion', ['source_artifact_id'], unique=False)
    op.create_table('link_assertion',
    sa.Column('link_type_id', sa.UUID(), nullable=False),
    sa.Column('source_type_id', sa.UUID(), nullable=False),
    sa.Column('target_type_id', sa.UUID(), nullable=False),
    sa.Column('source_object_id', sa.UUID(), nullable=False),
    sa.Column('target_object_id', sa.UUID(), nullable=False),
    sa.Column('source_artifact_id', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_link_assertion_confidence_in_range')),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name=op.f('ck_link_assertion_validity_ordered')),
    sa.ForeignKeyConstraint(['link_type_id', 'source_type_id', 'target_type_id'], ['ontology_link_type.id', 'ontology_link_type.source_type_id', 'ontology_link_type.target_type_id'], name='fk_link_assertion_link_type_endpoints', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['source_artifact.id'], name=op.f('fk_link_assertion_source_artifact_id_source_artifact'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_object_id', 'source_type_id'], ['object_ref.id', 'object_ref.object_type_id'], name='fk_link_assertion_source_object_type', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_object_id', 'target_type_id'], ['object_ref.id', 'object_ref.object_type_id'], name='fk_link_assertion_target_object_type', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_link_assertion'))
    )
    op.create_index('ix_link_assertion_active_link_source_target', 'link_assertion', ['link_type_id', 'source_object_id', 'target_object_id'], unique=False, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_index('ix_link_assertion_link_source_target_time', 'link_assertion', ['link_type_id', 'source_object_id', 'target_object_id', 'valid_from'], unique=False)
    op.create_index('ix_link_assertion_link_type_endpoints', 'link_assertion', ['link_type_id', 'source_type_id', 'target_type_id'], unique=False)
    op.create_index('ix_link_assertion_source_artifact', 'link_assertion', ['source_artifact_id'], unique=False)
    op.create_index('ix_link_assertion_source_type', 'link_assertion', ['source_object_id', 'source_type_id'], unique=False)
    op.create_index('ix_link_assertion_target_type', 'link_assertion', ['target_object_id', 'target_type_id'], unique=False)
    op.create_table('olympiad_benefit',
    sa.Column('olympiad_profile_id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('result_type_id', sa.UUID(), nullable=False),
    sa.Column('benefit_type_id', sa.UUID(), nullable=False),
    sa.Column('confirmation_score', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('confirmation_score IS NULL OR confirmation_score >= 0', name=op.f('ck_olympiad_benefit_confirmation_score_nonnegative')),
    sa.ForeignKeyConstraint(['benefit_type_id'], ['benefit_type.id'], name=op.f('fk_olympiad_benefit_benefit_type_id_benefit_type'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['offering_id'], ['program_offering.id'], name=op.f('fk_olympiad_benefit_offering_id_program_offering'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['olympiad_profile_id'], ['olympiad_profile.id'], name=op.f('fk_olympiad_benefit_olympiad_profile_id_olympiad_profile'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['result_type_id'], ['olympiad_result_type.id'], name=op.f('fk_olympiad_benefit_result_type_id_olympiad_result_type'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_olympiad_benefit')),
    sa.UniqueConstraint('olympiad_profile_id', 'offering_id', 'result_type_id', 'benefit_type_id', name='uq_olympiad_benefit_business_key')
    )
    op.create_index('ix_olympiad_benefit_benefit_type', 'olympiad_benefit', ['benefit_type_id'], unique=False)
    op.create_index('ix_olympiad_benefit_offering', 'olympiad_benefit', ['offering_id'], unique=False)
    op.create_index('ix_olympiad_benefit_result_type', 'olympiad_benefit', ['result_type_id'], unique=False)
    op.create_table('requirement_set',
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_requirement_set_name_not_blank')),
    sa.ForeignKeyConstraint(['offering_id'], ['program_offering.id'], name=op.f('fk_requirement_set_offering_id_program_offering'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_set')),
    sa.UniqueConstraint('offering_id', 'name', name='uq_requirement_set_offering_name')
    )
    op.create_table('rule_set_member',
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_set.id'], name=op.f('fk_rule_set_member_rule_set_id_rule_set'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_version_id', 'rule_id'], ['policy_rule_version.id', 'policy_rule_version.rule_id'], name='fk_rule_set_member_version_rule', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('rule_set_id', 'rule_version_id', name=op.f('pk_rule_set_member')),
    sa.UniqueConstraint('rule_set_id', 'rule_id', name='uq_rule_set_member_one_version_per_rule')
    )
    op.create_index('ix_rule_set_member_rule_version', 'rule_set_member', ['rule_version_id', 'rule_id'], unique=False)
    op.create_table('user_shortlist',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('offering_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['program_offering.id'], name=op.f('fk_user_shortlist_offering_id_program_offering'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profile.id'], name=op.f('fk_user_shortlist_profile_id_user_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'offering_id', name=op.f('pk_user_shortlist'))
    )
    op.create_index('ix_user_shortlist_offering', 'user_shortlist', ['offering_id'], unique=False)
    op.create_table('admission_statistic',
    sa.Column('pool_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('passing_score', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('average_score', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('enrolled_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('average_score IS NULL OR average_score >= 0', name=op.f('ck_admission_statistic_average_score_nonnegative')),
    sa.CheckConstraint('enrolled_count IS NULL OR enrolled_count >= 0', name=op.f('ck_admission_statistic_enrolled_count_nonnegative')),
    sa.CheckConstraint('passing_score IS NULL OR passing_score >= 0', name=op.f('ck_admission_statistic_passing_score_nonnegative')),
    sa.CheckConstraint('year >= 1900', name=op.f('ck_admission_statistic_year_valid')),
    sa.ForeignKeyConstraint(['pool_id'], ['competition_pool.id'], name=op.f('fk_admission_statistic_pool_id_competition_pool'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admission_statistic')),
    sa.UniqueConstraint('pool_id', 'year', name='uq_admission_statistic_pool_year')
    )
    op.create_table('requirement_node',
    sa.Column('requirement_set_id', sa.UUID(), nullable=False),
    sa.Column('parent_node_id', sa.UUID(), nullable=True),
    sa.Column('exam_id', sa.UUID(), nullable=True),
    sa.Column('node_type', sa.Text(), nullable=False),
    sa.Column('operator_type', sa.Text(), nullable=True),
    sa.Column('min_score', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('min_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("(node_type = 'exam' AND exam_id IS NOT NULL AND operator_type IS NULL AND min_count IS NULL) OR (node_type = 'operator' AND exam_id IS NULL AND operator_type IS NOT NULL AND min_score IS NULL AND ((operator_type = 'at_least' AND min_count IS NOT NULL AND min_count > 0) OR (operator_type IN ('and', 'or') AND min_count IS NULL)))", name=op.f('ck_requirement_node_node_shape_valid')),
    sa.CheckConstraint("node_type IN ('exam', 'operator')", name=op.f('ck_requirement_node_node_type_valid')),
    sa.CheckConstraint("operator_type IS NULL OR operator_type IN ('and', 'or', 'at_least')", name=op.f('ck_requirement_node_operator_type_valid')),
    sa.CheckConstraint('min_score IS NULL OR min_score >= 0', name=op.f('ck_requirement_node_min_score_nonnegative')),
    sa.CheckConstraint('parent_node_id IS NULL OR parent_node_id <> id', name=op.f('ck_requirement_node_not_own_parent')),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], name=op.f('fk_requirement_node_exam_id_exam'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requirement_set_id', 'parent_node_id'], ['requirement_node.requirement_set_id', 'requirement_node.id'], name='fk_requirement_node_parent_same_set', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requirement_set_id'], ['requirement_set.id'], name=op.f('fk_requirement_node_requirement_set_id_requirement_set'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_node')),
    sa.UniqueConstraint('requirement_set_id', 'id', name='uq_requirement_node_set_id')
    )
    op.create_index('ix_requirement_node_exam', 'requirement_node', ['exam_id'], unique=False)
    op.create_index('ix_requirement_node_set_parent', 'requirement_node', ['requirement_set_id', 'parent_node_id'], unique=False)
    op.create_index('ix_requirement_node_parent', 'requirement_node', ['parent_node_id'], unique=False)
    op.create_index('uq_requirement_node_single_root', 'requirement_node', ['requirement_set_id'], unique=True, postgresql_where=sa.text('parent_node_id IS NULL'))

    op.execute("""
    CREATE FUNCTION andromeda_validate_requirement_set(p_requirement_set_id uuid)
    RETURNS void
    LANGUAGE plpgsql
    AS $$
    DECLARE
        has_cycle boolean;
        invalid_node uuid;
    BEGIN
        WITH RECURSIVE parent_walk(start_id, node_id, parent_node_id, path, cycle) AS (
            SELECT n.id, n.id, n.parent_node_id, ARRAY[n.id], false
            FROM requirement_node AS n
            WHERE n.requirement_set_id = p_requirement_set_id
            UNION ALL
            SELECT w.start_id, parent.id, parent.parent_node_id,
                   w.path || parent.id, parent.id = ANY(w.path)
            FROM parent_walk AS w
            JOIN requirement_node AS parent
              ON parent.requirement_set_id = p_requirement_set_id
             AND parent.id = w.parent_node_id
            WHERE w.parent_node_id IS NOT NULL AND NOT w.cycle
        )
        SELECT EXISTS (SELECT 1 FROM parent_walk WHERE cycle)
        INTO has_cycle;

        IF has_cycle THEN
            RAISE EXCEPTION 'requirement_set % contains a parent cycle', p_requirement_set_id
                USING ERRCODE = '23514';
        END IF;

        SELECT n.id
        INTO invalid_node
        FROM requirement_node AS n
        LEFT JOIN requirement_node AS child
          ON child.requirement_set_id = n.requirement_set_id
         AND child.parent_node_id = n.id
        WHERE n.requirement_set_id = p_requirement_set_id
        GROUP BY n.id, n.node_type, n.operator_type, n.min_count
        HAVING (n.node_type = 'exam' AND count(child.id) <> 0)
            OR (n.node_type = 'operator' AND n.operator_type IN ('and', 'or') AND count(child.id) < 2)
            OR (n.node_type = 'operator' AND n.operator_type = 'at_least' AND count(child.id) < n.min_count)
        LIMIT 1;

        IF FOUND THEN
            RAISE EXCEPTION 'requirement_node % has an invalid child count', invalid_node
                USING ERRCODE = '23514';
        END IF;
    END;
    $$;
    """)

    op.execute("""
    CREATE FUNCTION andromeda_check_requirement_node_tree()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
        IF TG_OP = 'DELETE' THEN
            PERFORM andromeda_validate_requirement_set(OLD.requirement_set_id);
        ELSIF TG_OP = 'UPDATE' THEN
            PERFORM andromeda_validate_requirement_set(OLD.requirement_set_id);
            IF NEW.requirement_set_id <> OLD.requirement_set_id THEN
                PERFORM andromeda_validate_requirement_set(NEW.requirement_set_id);
            END IF;
        ELSE
            PERFORM andromeda_validate_requirement_set(NEW.requirement_set_id);
        END IF;
        RETURN NULL;
    END;
    $$;
    """)

    op.execute("""
    CREATE CONSTRAINT TRIGGER trg_requirement_node_tree_valid
    AFTER INSERT OR UPDATE OR DELETE ON requirement_node
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION andromeda_check_requirement_node_tree();
    """)

    op.execute("""
    CREATE FUNCTION andromeda_guard_policy_rule_version()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
        IF TG_OP = 'INSERT' THEN
            IF NEW.status <> 'draft' THEN
                RAISE EXCEPTION 'policy rule versions must be created as draft'
                    USING ERRCODE = '55000';
            END IF;
            RETURN NEW;
        END IF;

        IF OLD.status = 'published' THEN
            RAISE EXCEPTION 'published policy rule versions are immutable'
                USING ERRCODE = '55000';
        END IF;

        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;

        IF TG_OP = 'UPDATE' AND NEW.status = 'published' THEN
            PERFORM 1 FROM policy_rule WHERE id = NEW.rule_id FOR SHARE;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'policy rule % does not exist', NEW.rule_id
                    USING ERRCODE = '23503';
            END IF;
        END IF;
        RETURN NEW;
    END;
    $$;
    """)

    op.execute("""
    CREATE TRIGGER trg_policy_rule_version_immutable
    BEFORE INSERT OR UPDATE OR DELETE ON policy_rule_version
    FOR EACH ROW EXECUTE FUNCTION andromeda_guard_policy_rule_version();
    """)

    op.execute("""
    CREATE FUNCTION andromeda_guard_policy_rule()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
        IF EXISTS (
            SELECT 1 FROM policy_rule_version
            WHERE rule_id = OLD.id AND status = 'published'
        ) THEN
            RAISE EXCEPTION 'a policy rule with a published version is immutable'
                USING ERRCODE = '55000';
        END IF;
        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;
        RETURN NEW;
    END;
    $$;
    """)

    op.execute("""
    CREATE TRIGGER trg_policy_rule_immutable_after_publish
    BEFORE UPDATE OR DELETE ON policy_rule
    FOR EACH ROW EXECUTE FUNCTION andromeda_guard_policy_rule();
    """)

    op.execute("""
    CREATE FUNCTION andromeda_guard_rule_set()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
        IF TG_OP = 'INSERT' THEN
            IF NEW.status <> 'draft' THEN
                RAISE EXCEPTION 'rule sets must be created as draft'
                    USING ERRCODE = '55000';
            END IF;
            RETURN NEW;
        END IF;

        IF OLD.status = 'published' THEN
            RAISE EXCEPTION 'published rule sets are immutable'
                USING ERRCODE = '55000';
        END IF;

        IF TG_OP = 'UPDATE' AND NEW.status = 'published' THEN
            IF NOT EXISTS (
                SELECT 1 FROM rule_set_member WHERE rule_set_id = NEW.id
            ) THEN
                RAISE EXCEPTION 'a rule set must contain at least one published rule version'
                    USING ERRCODE = '23514';
            END IF;
            IF EXISTS (
                SELECT 1
                FROM rule_set_member AS member
                JOIN policy_rule_version AS version
                  ON version.id = member.rule_version_id
                 AND version.rule_id = member.rule_id
                WHERE member.rule_set_id = NEW.id AND version.status <> 'published'
            ) THEN
                RAISE EXCEPTION 'a published rule set may contain only published rule versions'
                    USING ERRCODE = '23514';
            END IF;
        END IF;

        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;
        RETURN NEW;
    END;
    $$;
    """)

    op.execute("""
    CREATE TRIGGER trg_rule_set_immutable_after_publish
    BEFORE INSERT OR UPDATE OR DELETE ON rule_set
    FOR EACH ROW EXECUTE FUNCTION andromeda_guard_rule_set();
    """)

    op.execute("""
    CREATE FUNCTION andromeda_guard_rule_set_member()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
        parent_status text;
        version_status text;
        parent_id uuid;
    BEGIN
        IF TG_OP = 'UPDATE' THEN
            RAISE EXCEPTION 'rule_set_member rows are changed by delete and insert'
                USING ERRCODE = '55000';
        END IF;

        IF TG_OP = 'DELETE' THEN
            parent_id := OLD.rule_set_id;
        ELSE
            parent_id := NEW.rule_set_id;
        END IF;

        SELECT status INTO parent_status
        FROM rule_set WHERE id = parent_id FOR UPDATE;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'rule set % does not exist', parent_id USING ERRCODE = '23503';
        END IF;
        IF parent_status <> 'draft' THEN
            RAISE EXCEPTION 'members of a published rule set are immutable'
                USING ERRCODE = '55000';
        END IF;

        IF TG_OP = 'INSERT' THEN
            SELECT status INTO version_status
            FROM policy_rule_version WHERE id = NEW.rule_version_id FOR SHARE;
            IF NOT FOUND OR version_status <> 'published' THEN
                RAISE EXCEPTION 'rule sets may include only published rule versions'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END IF;
        RETURN OLD;
    END;
    $$;
    """)

    op.execute("""
    CREATE TRIGGER trg_rule_set_member_immutable_after_publish
    BEFORE INSERT OR UPDATE OR DELETE ON rule_set_member
    FOR EACH ROW EXECUTE FUNCTION andromeda_guard_rule_set_member();
    """)

    op.execute("""
    CREATE FUNCTION andromeda_validate_fact_assertion_value()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
        property_data_type text;
    BEGIN
        SELECT data_type INTO property_data_type
        FROM ontology_property_type
        WHERE id = NEW.property_type_id
          AND object_type_id = NEW.object_type_id;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'property type does not belong to fact object type'
                USING ERRCODE = '23503';
        END IF;

        BEGIN
            CASE property_data_type
                WHEN 'string' THEN NULL;
                WHEN 'integer' THEN PERFORM NEW.value::bigint;
                WHEN 'decimal' THEN PERFORM NEW.value::numeric;
                WHEN 'boolean' THEN PERFORM NEW.value::boolean;
                WHEN 'date' THEN PERFORM NEW.value::date;
                WHEN 'datetime' THEN PERFORM NEW.value::timestamptz;
                WHEN 'json' THEN PERFORM NEW.value::jsonb;
                WHEN 'uuid' THEN PERFORM NEW.value::uuid;
                ELSE
                    RAISE EXCEPTION 'unsupported ontology property data type %', property_data_type
                        USING ERRCODE = '23514';
            END CASE;
        EXCEPTION
            WHEN invalid_text_representation OR numeric_value_out_of_range
                OR datetime_field_overflow OR invalid_datetime_format THEN
                RAISE EXCEPTION 'fact assertion value is not valid for ontology type %', property_data_type
                    USING ERRCODE = '23514';
        END;
        RETURN NEW;
    END;
    $$;
    """)

    op.execute("""
    CREATE TRIGGER trg_fact_assertion_value_type
    BEFORE INSERT OR UPDATE OF value, object_type_id, property_type_id ON fact_assertion
    FOR EACH ROW EXECUTE FUNCTION andromeda_validate_fact_assertion_value();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_rule_set_member_immutable_after_publish ON rule_set_member")
    op.execute("DROP FUNCTION IF EXISTS andromeda_guard_rule_set_member()")
    op.execute("DROP TRIGGER IF EXISTS trg_fact_assertion_value_type ON fact_assertion")
    op.execute("DROP FUNCTION IF EXISTS andromeda_validate_fact_assertion_value()")
    op.execute("DROP TRIGGER IF EXISTS trg_rule_set_immutable_after_publish ON rule_set")
    op.execute("DROP FUNCTION IF EXISTS andromeda_guard_rule_set()")
    op.execute("DROP TRIGGER IF EXISTS trg_policy_rule_immutable_after_publish ON policy_rule")
    op.execute("DROP FUNCTION IF EXISTS andromeda_guard_policy_rule()")
    op.execute("DROP TRIGGER IF EXISTS trg_policy_rule_version_immutable ON policy_rule_version")
    op.execute("DROP FUNCTION IF EXISTS andromeda_guard_policy_rule_version()")
    op.execute("DROP TRIGGER IF EXISTS trg_requirement_node_tree_valid ON requirement_node")
    op.execute("DROP FUNCTION IF EXISTS andromeda_check_requirement_node_tree()")
    op.execute("DROP FUNCTION IF EXISTS andromeda_validate_requirement_set(uuid)")
    op.drop_index('uq_requirement_node_single_root', table_name='requirement_node', postgresql_where=sa.text('parent_node_id IS NULL'))
    op.drop_index('ix_requirement_node_parent', table_name='requirement_node')
    op.drop_index('ix_requirement_node_set_parent', table_name='requirement_node')
    op.drop_index('ix_requirement_node_exam', table_name='requirement_node')
    op.drop_table('requirement_node')
    op.drop_table('admission_statistic')
    op.drop_index('ix_user_shortlist_offering', table_name='user_shortlist')
    op.drop_table('user_shortlist')
    op.drop_index('ix_rule_set_member_rule_version', table_name='rule_set_member')
    op.drop_table('rule_set_member')
    op.drop_table('requirement_set')
    op.drop_index('ix_olympiad_benefit_result_type', table_name='olympiad_benefit')
    op.drop_index('ix_olympiad_benefit_offering', table_name='olympiad_benefit')
    op.drop_index('ix_olympiad_benefit_benefit_type', table_name='olympiad_benefit')
    op.drop_table('olympiad_benefit')
    op.drop_index('ix_link_assertion_target_type', table_name='link_assertion')
    op.drop_index('ix_link_assertion_source_type', table_name='link_assertion')
    op.drop_index('ix_link_assertion_source_artifact', table_name='link_assertion')
    op.drop_index('ix_link_assertion_link_type_endpoints', table_name='link_assertion')
    op.drop_index('ix_link_assertion_link_source_target_time', table_name='link_assertion')
    op.drop_index('ix_link_assertion_active_link_source_target', table_name='link_assertion', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_table('link_assertion')
    op.drop_index('ix_fact_assertion_source_artifact', table_name='fact_assertion')
    op.drop_index('ix_fact_assertion_property_object_type', table_name='fact_assertion')
    op.drop_index('ix_fact_assertion_object_ref_type', table_name='fact_assertion')
    op.drop_index('ix_fact_assertion_object_property_time', table_name='fact_assertion')
    op.drop_index('ix_fact_assertion_active_object_property', table_name='fact_assertion', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_table('fact_assertion')
    op.drop_index('ix_curriculum_item_course', table_name='curriculum_item')
    op.drop_table('curriculum_item')
    op.drop_index('ix_competition_pool_quota_type', table_name='competition_pool')
    op.drop_index('ix_competition_pool_funding_type', table_name='competition_pool')
    op.drop_table('competition_pool')
    op.drop_index('ix_user_olympiad_result_type', table_name='user_olympiad')
    op.drop_index('ix_user_olympiad_olympiad_profile', table_name='user_olympiad')
    op.drop_table('user_olympiad')
    op.drop_index('ix_source_artifact_source_retrieved_at', table_name='source_artifact')
    op.drop_table('source_artifact')
    op.drop_table('rule_set')
    op.drop_index('ix_program_offering_program_university', table_name='program_offering')
    op.drop_index('ix_program_offering_campaign_university', table_name='program_offering')
    op.drop_table('program_offering')
    op.drop_index('ix_program_department_program_university', table_name='program_department')
    op.drop_index('ix_program_department_department_university', table_name='program_department')
    op.drop_table('program_department')
    op.drop_index('ix_policy_rule_version_published_validity', table_name='policy_rule_version', postgresql_where=sa.text("status = 'published'"))
    op.drop_table('policy_rule_version')
    op.drop_table('curriculum')
    op.drop_index('ix_user_exam_exam', table_name='user_exam')
    op.drop_table('user_exam')
    op.drop_index('ix_source_source_type', table_name='source')
    op.drop_table('source')
    op.drop_table('program')
    op.drop_index('ix_policy_rule_rule_type', table_name='policy_rule')
    op.drop_table('policy_rule')
    op.drop_table('ontology_property_type')
    op.drop_index('ix_ontology_link_type_target_type', table_name='ontology_link_type')
    op.drop_index('ix_ontology_link_type_source_type', table_name='ontology_link_type')
    op.drop_table('ontology_link_type')
    op.drop_table('olympiad_profile')
    op.drop_table('object_ref')
    op.drop_table('department')
    op.drop_table('course')
    op.drop_table('admission_campaign')
    op.drop_table('user_profile')
    op.drop_table('university')
    op.drop_index('ix_subject_area_parent', table_name='subject_area')
    op.drop_table('subject_area')
    op.drop_table('source_type')
    op.drop_table('quota_type')
    op.drop_table('policy_rule_type')
    op.drop_table('ontology_object_type')
    op.drop_table('olympiad_result_type')
    op.drop_table('olympiad')
    op.drop_table('funding_type')
    op.drop_table('exam')
    op.drop_table('benefit_type')
    # ### end Alembic commands ###
